[project]
name = "terminal-homepage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
    "sanic>=25.12.0",
    "toml>=0.10.2",
]
